### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by greut**
Some manual changes as well as 2to3 suggestions.

- optional `irisclient`, `slackclient`

### CODE REVIEW

**Comment by jrgp** [comment]
Why remove ujson?

**Comment by greut** [comment]
Rebased on master.

**Comment by diegocepedaw** [comment]
python 3 support exists in py3 branch

**Comment by webermanish** [comment]
Is the py3 version stable and usable in production?

**Comment by diegocepedaw** [comment]
@webermanish, the [py3 branch](https://github.com/linkedin/oncall/tree/py3) is what we currently use in production and is the most up to date branch.

**Pull request closed without merging**
